name: Latest Release
on:
  release:
    types:
      - published
jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Build & Publish
        run: |
          pnpm install
          pnpm build
          pnpm build:storybook
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
